local lib = _G["LibMapData"]

lib.mapIndexData = {
  [1] = {
    ["mapTexture"] = "",
    ["mapIndex"] = 1,
    ["mapId"] = 27, -- 0 zoneInfo
    ["zoneIndex"] = 1,
    ["zoneName"] = "Tamriel",
    ["zoneId"] = 0, -- 2  zoneInfo
  },
  [2] = {
    ["mapTexture"] = "glenumbra/glenumbra_base_0",
    ["mapIndex"] = 2,
    ["mapId"] = 1,
    ["zoneIndex"] = 2,
    ["zoneName"] = "Glenumbra",
    ["zoneId"] = 3,
  },
  [3] = {
    ["mapTexture"] = "rivenspire/rivenspire_base_0",
    ["mapIndex"] = 3,
    ["mapId"] = 10,
    ["zoneIndex"] = 5,
    ["zoneName"] = "Rivenspire",
    ["zoneId"] = 20,
  },
  [4] = {
    ["mapTexture"] = "stormhaven/stormhaven_base_0",
    ["mapIndex"] = 4,
    ["mapId"] = 12,
    ["zoneIndex"] = 4,
    ["zoneName"] = "Stormhaven",
    ["zoneId"] = 19,
  },
  [5] = {
    ["mapTexture"] = "alikr/alikr_base_0",
    ["mapIndex"] = 5,
    ["mapId"] = 30,
    ["zoneIndex"] = 17,
    ["zoneName"] = "Alik'r Desert",
    ["zoneId"] = 104,
  },
  [6] = {
    ["mapTexture"] = "bangkorai/bangkorai_base_0",
    ["mapIndex"] = 6,
    ["mapId"] = 20,
    ["zoneIndex"] = 14,
    ["zoneName"] = "Bangkorai",
    ["zoneId"] = 92,
  },
  [7] = {
    ["mapTexture"] = "grahtwood/grahtwood_base_0",
    ["mapIndex"] = 7,
    ["mapId"] = 9,
    ["zoneIndex"] = 180,
    ["zoneName"] = "Grahtwood",
    ["zoneId"] = 383,
  },
  [8] = {
    ["mapTexture"] = "malabaltor/malabaltor_base_0",
    ["mapIndex"] = 8,
    ["mapId"] = 22,
    ["zoneIndex"] = 11,
    ["zoneName"] = "Malabal Tor",
    ["zoneId"] = 58,
  },
  [9] = {
    ["mapTexture"] = "shadowfen/shadowfen_base_0",
    ["mapIndex"] = 9,
    ["mapId"] = 26,
    ["zoneIndex"] = 19,
    ["zoneName"] = "Shadowfen",
    ["zoneId"] = 117,
  },
  [10] = {
    ["mapTexture"] = "deshaan/deshaan_base_0",
    ["mapIndex"] = 10,
    ["mapId"] = 13,
    ["zoneIndex"] = 10,
    ["zoneName"] = "Deshaan",
    ["zoneId"] = 57,
  },
  [11] = {
    ["mapTexture"] = "stonefalls/stonefalls_base_0",
    ["mapIndex"] = 11,
    ["mapId"] = 7,
    ["zoneIndex"] = 9,
    ["zoneName"] = "Stonefalls",
    ["zoneId"] = 41,
  },
  [12] = {
    ["mapTexture"] = "therift/therift_base_0",
    ["mapIndex"] = 12,
    ["mapId"] = 125,
    ["zoneIndex"] = 16,
    ["zoneName"] = "The Rift",
    ["zoneId"] = 103,
  },
  [13] = {
    ["mapTexture"] = "eastmarch/eastmarch_base_0",
    ["mapIndex"] = 13,
    ["mapId"] = 61,
    ["zoneIndex"] = 15,
    ["zoneName"] = "Eastmarch",
    ["zoneId"] = 101,
  },
  [14] = {
    ["mapTexture"] = "cyrodiil/ava_whole_0",
    ["mapIndex"] = 14,
    ["mapId"] = 16,
    ["zoneIndex"] = 37,
    ["zoneName"] = "Cyrodiil",
    ["zoneId"] = 181,
  },
  [15] = {
    ["mapTexture"] = "auridon/auridon_base_0",
    ["mapIndex"] = 15,
    ["mapId"] = 143,
    ["zoneIndex"] = 178,
    ["zoneName"] = "Auridon",
    ["zoneId"] = 381,
  },
  [16] = {
    ["mapTexture"] = "greenshade/greenshade_base_0",
    ["mapIndex"] = 16,
    ["mapId"] = 300,
    ["zoneIndex"] = 18,
    ["zoneName"] = "Greenshade",
    ["zoneId"] = 108,
  },
  [17] = {
    ["mapTexture"] = "reapersmarch/reapersmarch_base_0",
    ["mapIndex"] = 17,
    ["mapId"] = 256,
    ["zoneIndex"] = 179,
    ["zoneName"] = "Reaper's March",
    ["zoneId"] = 382,
  },
  [18] = {
    ["mapTexture"] = "stonefalls/balfoyen_base_0",
    ["mapIndex"] = 18,
    ["mapId"] = 75,
    ["zoneIndex"] = 110,
    ["zoneName"] = "Bal Foyen",
    ["zoneId"] = 281,
  },
  [19] = {
    ["mapTexture"] = "glenumbra/strosmkai_base_0",
    ["mapIndex"] = 19,
    ["mapId"] = 201,
    ["zoneIndex"] = 304,
    ["zoneName"] = "Stros M'Kai",
    ["zoneId"] = 534,
  },
  [20] = {
    ["mapTexture"] = "glenumbra/betnihk_base_0",
    ["mapIndex"] = 20,
    ["mapId"] = 227,
    ["zoneIndex"] = 305,
    ["zoneName"] = "Betnikh",
    ["zoneId"] = 535,
  },
  [21] = {
    ["mapTexture"] = "auridon/khenarthisroost_base_0",
    ["mapIndex"] = 21,
    ["mapId"] = 258,
    ["zoneIndex"] = 306,
    ["zoneName"] = "Khenarthi's Roost",
    ["zoneId"] = 537,
  },
  [22] = {
    ["mapTexture"] = "stonefalls/bleakrock_base_0",
    ["mapIndex"] = 22,
    ["mapId"] = 74,
    ["zoneIndex"] = 109,
    ["zoneName"] = "Bleakrock Isle",
    ["zoneId"] = 280,
  },
  [23] = {
    ["mapTexture"] = "coldharbor/coldharbour_base_0",
    ["mapIndex"] = 23,
    ["mapId"] = 255,
    ["zoneIndex"] = 154,
    ["zoneName"] = "Coldharbour",
    ["zoneId"] = 347,
  },
  [24] = {
    ["mapTexture"] = "",
    ["mapIndex"] = 24,
    ["mapId"] = 439, -- 0 zoneInfo
    ["zoneIndex"] = 1,
    ["zoneName"] = "The Aurbis",
    ["zoneId"] = 0, -- 2 zoneInfo
  },
  [25] = {
    ["mapTexture"] = "craglorn/craglorn_base_0",
    ["mapIndex"] = 25,
    ["mapId"] = 1126,
    ["zoneIndex"] = 500,
    ["zoneName"] = "Craglorn",
    ["zoneId"] = 888,
  },
  [26] = {
    ["mapTexture"] = "cyrodiil/imperialcity_base_0",
    ["mapIndex"] = 26,
    ["mapId"] = 660,
    ["zoneIndex"] = 346,
    ["zoneName"] = "Imperial City",
    ["zoneId"] = 584,
  },
  [27] = {
    ["mapTexture"] = "wrothgar/wrothgar_base_0",
    ["mapIndex"] = 27,
    ["mapId"] = 667,
    ["zoneIndex"] = 379,
    ["zoneName"] = "Wrothgar",
    ["zoneId"] = 684,
  },
  [28] = {
    ["mapTexture"] = "thievesguild/hewsbane_base_0",
    ["mapIndex"] = 28,
    ["mapId"] = 994,
    ["zoneIndex"] = 442,
    ["zoneName"] = "Hew's Bane",
    ["zoneId"] = 816,
  },
  [29] = {
    ["mapTexture"] = "darkbrotherhood/goldcoast_base_0",
    ["mapIndex"] = 29,
    ["mapId"] = 1006,
    ["zoneIndex"] = 448,
    ["zoneName"] = "Gold Coast",
    ["zoneId"] = 823,
  },
  [30] = {
    ["mapTexture"] = "vvardenfell/vvardenfell_base_0",
    ["mapIndex"] = 30,
    ["mapId"] = 1060,
    ["zoneIndex"] = 467,
    ["zoneName"] = "Vvardenfell",
    ["zoneId"] = 849,
  },
  [31] = {
    ["mapTexture"] = "clockwork/clockwork_base_0",
    ["mapIndex"] = 31,
    ["mapId"] = 1313,
    ["zoneIndex"] = 589,
    ["zoneName"] = "Clockwork City",
    ["zoneId"] = 980,
  },
  [32] = {
    ["mapTexture"] = "summerset/summerset_base_0",
    ["mapIndex"] = 32,
    ["mapId"] = 1349,
    ["zoneIndex"] = 616,
    ["zoneName"] = "Summerset",
    ["zoneId"] = 1011,
  },
  [33] = {
    ["mapTexture"] = "summerset/artaeum_base_0",
    ["mapIndex"] = 33,
    ["mapId"] = 1429,
    ["zoneIndex"] = 632,
    ["zoneName"] = "Artaeum",
    ["zoneId"] = 1027,
  },
  [34] = {
    ["mapTexture"] = "murkmire/murkmire_base_0",
    ["mapIndex"] = 34,
    ["mapId"] = 1484,
    ["zoneIndex"] = 407,
    ["zoneName"] = "Murkmire",
    ["zoneId"] = 726,
  },
  [35] = {
    ["mapTexture"] = "murkmire/swampisland_ext_base_0",
    ["mapIndex"] = 35,
    ["mapId"] = 1552,
    ["zoneIndex"] = 668,
    ["zoneName"] = "Norg-Tzel",
    ["zoneId"] = 1072,
  },
  [36] = {
    ["mapTexture"] = "elsweyr/elsweyr_base_0",
    ["mapIndex"] = 36,
    ["mapId"] = 1555,
    ["zoneIndex"] = 681,
    ["zoneName"] = "Northern Elsweyr",
    ["zoneId"] = 1086,
  },
  [37] = {
    ["mapTexture"] = "southernelsweyr/southernelsweyr_base_0",
    ["mapIndex"] = 37,
    ["mapId"] = 1654,
    ["zoneIndex"] = 720,
    ["zoneName"] = "Southern Elsweyr",
    ["zoneId"] = 1133,
  },
  [38] = {
    ["mapTexture"] = "skyrim/westernskryim_base_0",
    ["mapIndex"] = 38,
    ["mapId"] = 1719,
    ["zoneIndex"] = 743,
    ["zoneName"] = "Western Skyrim",
    ["zoneId"] = 1160,
  },
  [39] = {
    ["mapTexture"] = "skyrim/blackreach_base_0",
    ["mapIndex"] = 39,
    ["mapId"] = 1747,
    ["zoneIndex"] = 744,
    ["zoneName"] = "Blackreach: Greymoor Caverns",
    ["zoneId"] = 1161,
  },
  [40] = -- nil dungeon nil main zone
  {
    ["mapTexture"] = "",
    ["mapIndex"] = 40,
    ["mapId"] = 1782, -- 0 zoneInfo
    ["zoneIndex"] = 1,
    ["zoneName"] = "Blackreach",
    ["zoneId"] = 0, -- 2 zoneInfo
  },
  [41] = {
    ["mapTexture"] = "reach/u28_blackreach_base_0",
    ["mapIndex"] = 41,
    ["mapId"] = 1850,
    ["zoneIndex"] = 784,
    ["zoneName"] = "Blackreach: Arkthzand Cavern",
    ["zoneId"] = 1208,
  },
  [42] = {
    ["mapTexture"] = "reach/reach_base_0",
    ["mapIndex"] = 42,
    ["mapId"] = 1814,
    ["zoneIndex"] = 783,
    ["zoneName"] = "The Reach",
    ["zoneId"] = 1207,
  },
  [43] = {
    ["mapTexture"] = "blackwood/blackwood_base_0",
    ["mapIndex"] = 43,
    ["mapId"] = 1887,
    ["zoneIndex"] = 834,
    ["zoneName"] = "Blackwood",
    ["zoneId"] = 1261,
  },
  [44] = {
    ["mapTexture"] = "deadlands/u32_fargravezone_base_0",
    ["mapIndex"] = 44,
    ["mapId"] = 2119,
    ["zoneIndex"] = 854,
    ["zoneName"] = "Fargrave",
    ["zoneId"] = 1283,
  },
  [45] = {
    ["mapTexture"] = "deadlands/u32deadlandszone_base_0",
    ["mapIndex"] = 45,
    ["mapId"] = 2021,
    ["zoneIndex"] = 857,
    ["zoneName"] = "The Deadlands",
    ["zoneId"] = 1286,
  },
}
